{"name": "test_allure_report[chrome]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\django_study\\\\pytest_test_framework\\\\tests\\\\screenshot\\\\2019-07-30_19_36_36_excepiton.png'", "trace": "..\\..\\common\\decorator.py:12: in wrapper\n    return func(*args, **kw)\npc\\test_cost_bill.py:611: in test_allure_report\n    assert result is not True, '登录失败！'\nE   AssertionError: 登录失败！\nE   assert True is not True\n\nDuring handling of the above exception, another exception occurred:\n..\\..\\common\\decorator.py:18: in wrapper\n    file = open(save, 'rb').read()\nE   FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\django_study\\\\pytest_test_framework\\\\tests\\\\screenshot\\\\2019-07-30_19_36_36_excepiton.png'"}, "attachments": [{"name": "log", "source": "6d677e06-9375-4e45-9891-92ef74f28d47-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f44a0724-d64c-43f3-9c27-35450eec36a2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "multi_browser_driver", "value": "'chrome'"}], "start": 1564486559549, "stop": 1564486596673, "uuid": "7d631691-36dd-4f42-b91b-68694c3eb6d5", "historyId": "55818c81663d44b0cef8c649e9c2873d", "fullName": "pc.test_cost_bill#test_allure_report[chrome]", "labels": [{"name": "feature", "value": "test"}, {"name": "tag", "value": "test"}, {"name": "parentSuite", "value": "pc"}, {"name": "suite", "value": "test_cost_bill"}, {"name": "subSuite"}, {"name": "host", "value": "W7-201707071701"}, {"name": "thread", "value": "12480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pc.test_cost_bill"}]}