{"name": "test_allure_report[chrome]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\django_study\\\\pytest_test_framework\\\\tests\\\\screenshot\\\\2019-07-31_17_39_07_excepiton.png'", "trace": "decorator.py:12: in wrapper\n    return func(*args, **kw)\npc\\test_cost_bill.py:615: in test_allure_report\n    assert result is not True, '登录失败！'\nE   AssertionError: 登录失败！\nE   assert True is not True\n\nDuring handling of the above exception, another exception occurred:\ndecorator.py:18: in wrapper\n    file = open(save, 'rb').read()\nE   FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\django_study\\\\pytest_test_framework\\\\tests\\\\screenshot\\\\2019-07-31_17_39_07_excepiton.png'"}, "attachments": [{"name": "log", "source": "e6584d85-6d03-4a4c-b12e-60e411396199-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "3a416360-60a9-4de7-9b3a-6cc08bfdd06a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "multi_browser_driver", "value": "'chrome'"}], "start": 1564565846663, "stop": 1564565948579, "uuid": "f63ccac0-9e0a-4704-81dc-9cd384a53990", "historyId": "55818c81663d44b0cef8c649e9c2873d", "fullName": "pc.test_cost_bill#test_allure_report[chrome]", "labels": [{"name": "feature", "value": "test"}, {"name": "tag", "value": "test"}, {"name": "parentSuite", "value": "pc"}, {"name": "suite", "value": "test_cost_bill"}, {"name": "subSuite"}, {"name": "host", "value": "W7-201707071701"}, {"name": "thread", "value": "7616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pc.test_cost_bill"}]}